TrialProject/TrialProject/Controllers/TrialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TrialProject.Models;

namespace TrialProject.Controllers
{
    public class TrialController : Controller
    {
        EmployeesystemContext _context;
        //ProfileAPIController _api;

        public TrialController(EmployeesystemContext context/*ProfileAPIController api*/)
        {
            _context = context;
            //_api = api;
        }

        //public IActionResult Index()
        //{
        //    ViewModel emp = null;

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("http://localhost:44319/api/");
        //        var responseTask = client.PostAsJsonAsync("ProfileAPI",1);

        //        //responseTask.Wait();

        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<ViewModel>();
        //            //readTask.Wait();

        //            emp = readTask.Result;
        //        }
        //        else
        //        {
        //            ModelState.AddModelError(string.Empty, "Server Error");
        //        }
        //    }

        //    return View(emp);
        //}

        //public ActionResult Index()
        //{
        //    ViewModel emp = null;

        //    HttpClient client= _api.
        //}

        //public async Task<ActionResult> Index()
        //{
        //    ViewModel emp = new ViewModel();

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:44319/api/");
        //        client.DefaultRequestHeaders.Clear();
        //        client.Timeout = TimeSpan.FromMinutes(5);

        //        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //        HttpResponseMessage Res = await client.PostAsJsonAsync("ProfileAPI",0);

        //        if (Res.IsSuccessStatusCode)
        //        {
        //            var EmpResponse = Res.Content.ReadAsStringAsync().Result;

        //            emp = JsonConvert.DeserializeObject<ViewModel>(EmpResponse);
        //        }
        //    }
        //    return View(emp);
        //}

        public async Task<ActionResult> Index()
        {
            List<ViewModel> view = new List<ViewModel>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44319/api/");
                client.DefaultRequestHeaders.Clear();
                client.Timeout = TimeSpan.FromMinutes(5);

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applicaiton/json"));

                HttpResponseMessage res = await client.GetAsync("ProfileAPI");
                if (res.IsSuccessStatusCode)
                {
                    var EmpResponse = res.Content.ReadAsStringAsync().Result;

                    view = JsonConvert.DeserializeObject<List<ViewModel>>(EmpResponse);
                }

                return View(view.Find(m=>m.UserId==0));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Create(Registration registration)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44319/api/");
                client.DefaultRequestHeaders.Clear();
                client.Timeout = TimeSpan.FromMinutes(5);

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage res = await client.PostAsJsonAsync<Registration>("ProfileAPI", registration);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

TrialProject/TrialProject/Views/Trial/Create.cshtml
@model TrialProject.Models.Registration
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-controller="Trial" asp-action="Create" method="post" class="form-horizontal" role="form">
    <style type="text/css">
        body {
            background-color: lightblue
        }
    </style>
    <div class="form-horizontal">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="UserName" class="form-control" />
                <font color="red">@ViewBag.ErrorUserName</font>
                <span asp-validation-for="UserName" class="text-danger"></span>



            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <font color="red">@ViewBag.ErrorEmail</font>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ConPass" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="ConPass" class="form-control" />
                <span asp-validation-for="ConPass" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="reset" value="Clear" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

TrialProject/TrialProject/Views/Trial/Index.cshtml
@model TrialProject.Models.ViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Details</h2>
<style type="text/css">
    body {
        background-color: #5ecb8c
    }
</style>

<div>
    <h4>Your Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <font size="4">Name</font>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmpFirstName)
            @Html.DisplayFor(model => model.EmpMidName)
            @Html.DisplayFor(model => model.EmpLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt>
            Date of Birth
        </dt>
        <dd>
            @Model.DOB.ToString(" dd MMMM yyyy")

            @*@Html.DisplayFor(model => model.DOB.Value.ToString("dd/mm/yyyy"))*@
        </dd>
        <dt>
            Department
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeptName)

        </dd>
        <dt>
            @Html.ActionLink("Edit", "Edit", "Profile", new { id = Model.UserId })

        </dt>
    </dl>
</div>