TrialProject/TrialProject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using TrialProject.Models;
using TrialProject.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace TrialProject.Controllers
{
    public interface ICipherService
    {
        string DecryptProtectedData(string encryptedText, string environmentVariableName);
    }

    public class LoginController : Controller, ICipherService
    {
        EmployeesystemContext _context;
        private readonly IDataProtectionProvider _dataProtectionProvider;
        private const string key = "Mxo26SnC91m6D3l0";

        public LoginController(EmployeesystemContext context, IDataProtectionProvider dataProtectionProvider)
        {
            _context = context;
            _dataProtectionProvider = dataProtectionProvider;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Details(LoginModel view)
        {
            if (view == null)
            {
                return NoContent();
            }
            Employee employee;

            if (CheckEmailOrNot(view.IdOrEmail) == true)
            {
                employee = _context.Employee.FirstOrDefault(d => d.Email == view.IdOrEmail);
            }
            else
            {
                employee = _context.Employee.Find(Convert.ToInt32(view.IdOrEmail));
            }


            if (employee == null)
            {
                return NoContent();
            }

            if (decryptFrom(employee.Pass) == view.Password)
            {
                HttpContext.Session.SetInt32("User", employee.UserId);
                return RedirectToAction("Details", "Profile", new { ID = employee.UserId });

            }
            else
            {
                ViewBag.error = "Password or User-ID don't match";
                return View("Index");
            }
        }
        public IActionResult Forgotpassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Forgotpassword(Employee employee)
        {
            if (employee == null)
            {
                return NoContent();
            }

            Employee emp = _context.Employee.FirstOrDefault(e => e.Email == employee.Email);
            if (emp != null && emp.UserId == employee.UserId)
            {
                MailMessage message = new MailMessage("yesashish123456@gmail.com", emp.Email);
                StringBuilder mailbody = new StringBuilder();

                mailbody.Append("click the below link to enter the new password");
                mailbody.Append("<br/>");
                mailbody.Append("https://localhost:44319/Login/Repassword/" + employee.UserId);
                message.IsBodyHtml = true;
                message.Body = mailbody.ToString();
                message.Subject = "reset password";
                SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587)
                {
                    Credentials = new System.Net.NetworkCredential("yesashish123456@gmail.com", "Aj@12345"),
                    EnableSsl = true
                };
                smtpClient.Send(message);
            }
            else
                ViewBag.Mismatch = "Email/User-ID does not exist";

            return View();

        }

        public IActionResult Repassword(int? id)
        {
            if (id == null)
            {
                return NoContent();
            }

            ConfirmPassword confirmPassword = new ConfirmPassword()
            {
                UserId = id
            };

            return View(confirmPassword);
        }

        [HttpPost]
        public IActionResult Repassword(ConfirmPassword confirmPassword)
        {
            if (confirmPassword == null)
            {
                return NoContent();
            }
            //var some=new
            Employee emp = _context.Employee.Find(confirmPassword.UserId);
            if (emp == null)
            {
                return NoContent();
            }


            if (confirmPassword.Password == confirmPassword.ConPass)
            {
                Employee password = _context.Employee.Find(confirmPassword.UserId);
                password.Pass = encryptTo(confirmPassword.Password);
                _context.SaveChanges();
                return View("Index");
            }
            else
            {
                ViewBag.Mismatch = "Passwords don't match!";
                return View(confirmPassword);
            }
        }

        public string decryptFrom(string S)
        {
            var decrypt = _dataProtectionProvider.CreateProtector(key);

            return decrypt.Unprotect(S);
        }

        public string encryptTo(string S)
        {
            var encrypt = _dataProtectionProvider.CreateProtector(key);

            return encrypt.Protect(S);
        }

        public string DecryptProtectedData(string encryptedText, string environmentVariableName)
        {
            throw new NotImplementedException();
        }

        public bool CheckEmailOrNot(string S)
        {
            if (S == null)
                return false;

            for (int i = 0; i < S.Length; i++)
            {
                if (char.IsLetter(Convert.ToChar(S.Substring(i, 1))))
                    return true;
            }

            return false;
        }
    }
}

TrialProject/TrialProject/Controllers/RegisterController.cs
using TrialProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using ReflectionIT.Mvc.Paging;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Text;
using Microsoft.AspNetCore.DataProtection;
using System.Net.Http;
using System.Net.Http.Headers;

namespace FirstProject.Controllers
{
    public interface ICipherService
    {
        string DecryptProtectedData(string encryptedText, string environmentVariableName);
    }

    public class RegisterController : Controller
    {
        private EmployeesystemContext _context;
        public RegisterController(EmployeesystemContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Registration registration)
        {
            Employee checkUserName = _context.Employee.SingleOrDefault(
                 m => m.UserName == registration.UserName);
            if (checkUserName == null)
            {
                Employee checkEmail = _context.Employee.SingleOrDefault(
                m => m.Email == registration.Email);

                if (checkEmail == null)
                {
                    if (ModelState.IsValid)
                    {
                        using (var client = new HttpClient())
                        {
                            client.BaseAddress = new Uri("https://localhost:44319/api/");
                            client.DefaultRequestHeaders.Clear();
                            client.Timeout = TimeSpan.FromMinutes(5);

                            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                            HttpResponseMessage Res = await client.PostAsJsonAsync<Registration>("RegisterAPI", registration);
                            if (Res.IsSuccessStatusCode)
                            {
                                return RedirectToAction("Success", new { id = _context.Employee.Last().UserId });
                            }
                        }
                    }
                }
                else
                {
                    ViewBag.ErrorEmail = "Email already exists";
                }
            }
            else
            {
                ViewBag.ErrorUserName = "UserName already exists";
                return View("Create");
            }


            return View(registration);
        }

        public IActionResult Success(int? id)
        {
            return View(_context.Employee.Find(id));
        }
    }
}

TrialProject/TrialProject/Views/Register/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model TrialProject.Models.Registration

<h2>New Registration</h2>

<h2>@ViewData["Title"]</h2>
<br />
<br />

<form asp-controller="Register" asp-action="Create" method="post" class="form-horizontal" role="form">
    <style type="text/css">
        body {
            background-color: lightblue
        }
    </style>
    <div class="form-horizontal">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group">
            <label asp-for="UserName" class="col-md-2 control-label"></label> 
            <div class="col-md-5">
                <input asp-for="UserName" class="form-control" />
                <font color="red">@ViewBag.ErrorUserName</font>
                <span asp-validation-for="UserName" class="text-danger"></span>



            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <font color="red">@ViewBag.ErrorEmail</font>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ConPass" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="ConPass" class="form-control" />
                <span asp-validation-for="ConPass" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="reset" value="Clear" class="btn btn-default" />
            </div>
        </div>

    </div>

    @Html.ActionLink("Go Back", "Index", "Login")
</form>

TrialProject/TrialProject/Views/Register/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

@model TrialProject.Models.Employee
<h6>Success</h6>
<style type="text/css">
    body {
        background-color: lightgreen
    }
</style>

<font size="5">
    <div class="col-lg-2">Your User ID is @Html.DisplayFor(modelItem => modelItem.UserId)</div>
</font>

@Html.ActionLink("Go to Login Page","Index","Login")